name: Testing TypeScript Custom Action

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testing TS Action
        uses: NeddM/testActionTS@main
        with:
          myname: "Nedd Chairi"
